#import "XPad.h"

@interface XPXPad : NSObject
@property (nonatomic,strong) TUISystemInputAssistantView *xpadAssistantView;
@property (nonatomic, strong) UIBarButtonItemGroup *XPadShortcutsGroup;
@property (nonatomic, strong) UIBarButtonItemGroup *XPadShortcutsBundleGroup;
@property (nonatomic, strong) UIBarButtonItemGroup *XPadShortcutsFloatGroup;
@property (nonatomic, strong) UIBarButtonItemGroup *XPadShortcutsBundleFloatGroup;
@property (nonatomic, strong) UIBarButtonItem *bundleButton;
@property (nonatomic, strong) UIBarButtonItem *bundleFloatButton;
@property (nonatomic, strong) NSMutableArray *XPadShortcuts;
@property (nonatomic, strong) NSMutableArray *XPadShortcutsBundle;
@property (nonatomic, strong) NSMutableArray *XPadShortcutsFloat;
@property (nonatomic, strong) NSMutableArray *XPadShortcutsBundleFloat;
@property (strong, nonatomic) NSMutableArray *kbType;
@property (strong, nonatomic) NSMutableArray *kbTypeLabel;
@property (nonatomic, assign) NSInteger trueKBType;
@property (nonatomic, strong) NSArray *XPadShortcutsDetails;
@property (nonatomic, assign) BOOL setLongPressGesture;
//@property (nonatomic, assign) BOOL shouldAddCopyLogButton;
@property (nonatomic, assign) BOOL refreshView;
@property (nonatomic, assign) TUISystemInputAssistantView * systemInputAssistantView;
@property (nonatomic, assign) NSTimer *cursorTimer;
@property (nonatomic, assign) NSTimer *cursorTimerRetest;
@property (nonatomic, assign) NSInteger cursorMovingFactor;
@property (nonatomic, assign) float cursorTimerSpeed;
@property (nonatomic, assign) float t;
@property (nonatomic, assign) BOOL isSameProcess;
@property (strong, nonatomic) UIBarButtonItem *autoCorrectionButton;
@property (strong, nonatomic) UIBarButtonItem *autoCapitalizationButton;
@property (strong, nonatomic) UIBarButtonItem *keyboardInputTypeButton;
@property (strong, nonatomic) UIBarButtonItem *loupeButton;
@property (nonatomic, assign) BOOL autoCorrectionEnabled;
@property (nonatomic, assign) BOOL autoCapitalizationEnabled;
@property (nonatomic, assign) BOOL loupeEnabled;
@property (nonatomic, strong) dispatch_block_t retestDispatchBlock;
@property (strong, nonatomic) CPDistributedMessagingCenter *xpadCenter;
@property (strong, nonatomic) CPDistributedMessagingCenter *toastCenter;
@property (strong, nonatomic) NSString *commandTitle;
@property (nonatomic, assign) NSInteger insertTextActionType;
@property (nonatomic, assign) BOOL moveCursorWithSelect;
@property (nonatomic, assign) BOOL isWordSender;
@property (nonatomic, strong) dispatch_block_t centerViewChangedDispatchBlock;
@property (nonatomic, assign) BOOL asyncUpdated;
@property (nonatomic, strong) NSString *parentActionName;
@property (strong, nonatomic) XPShortcutsGenerator *shortcutsGenerator;

-(void)shakeButton:(UIBarButtonItem *)sender;
-(void)shakeView:(UIView *)sender;
-(IBAction)selectAllAction:(UIBarButtonItem*)sender;
-(IBAction)copyAction:(UIBarButtonItem*)sender;
-(IBAction)pasteAction:(UIBarButtonItem*)sender;
-(IBAction)cutAction:(UIBarButtonItem*)sender;
-(IBAction)undoAction:(UIBarButtonItem*)sender;
-(IBAction)redoAction:(UIBarButtonItem*)sender;
-(IBAction)selectAction:(UIBarButtonItem*)sender;
-(IBAction)beginningAction:(UIBarButtonItem*)sender;
-(IBAction)endingAction:(UIBarButtonItem*)sender;
-(IBAction)capitalizeAction:(UIBarButtonItem*)sender;
-(IBAction)lowercaseAction:(UIBarButtonItem*)sender;
-(IBAction)uppercaseAction:(UIBarButtonItem*)sender;
-(IBAction)deleteAction:(UIBarButtonItem*)sender;
-(IBAction)deleteAllAction:(UIBarButtonItem*)sender;
-(IBAction)boldAction:(UIBarButtonItem*)sender;
-(IBAction)italicAction:(UIBarButtonItem*)sender;
-(IBAction)underlineAction:(UIBarButtonItem*)sender;
-(IBAction)dismissKeyboardAction:(UIBarButtonItem*)sender;
-(void)moveCursorLeftAction:(UIBarButtonItem*)sender;
-(void)moveCursorRightAction:(UIBarButtonItem*)sender;
-(void)moveCursorUpAction:(UIBarButtonItem*)sender;
-(void)moveCursorDownAction:(UIBarButtonItem*)sender;
-(void)keyboardTypeAction:(UIBarButtonItem*)sender;
-(void)defineAction:(UIBarButtonItem*)sender;
-(void)runCommandAction:(UIBarButtonItem*)sender;
-(void)insertTextAction:(UIBarButtonItem*)sender;
-(void)selectLineAction:(UIBarButtonItem*)sender;
-(void)selectParagraphAction:(UIBarButtonItem*)sender;
-(void)selectSentenceAction:(UIBarButtonItem*)sender;
-(void)moveCursorPreviousWordAction:(UIBarButtonItem*)sender;
-(void)moveCursorNextWordAction:(UIBarButtonItem*)sender;
-(void)moveCursorStartOfLineAction:(UIBarButtonItem*)sender;
-(void)moveCursorEndOfLineAction:(UIBarButtonItem*)sender;
-(void)moveCursorStartOfParagraphAction:(UIBarButtonItem*)sender;
-(void)moveCursorEndOfParagraphAction:(UIBarButtonItem*)sender;
-(void)moveCursorStartOfSentenceAction:(UIBarButtonItem*)sender;
-(void)moveCursorEndOfSentenceAction:(UIBarButtonItem*)sender;
-(void)copyLogAction:(UIBarButtonItem*)sender;
-(void)translomaticAction:(UIBarButtonItem *)sender;
-(void)wasabiAction:(UIBarButtonItem *)sender;
-(void)pasitheaAction:(UIBarButtonItem*)sender;
-(void)globeAction:(UIBarButtonItem*)sender;
-(void)dictationAction:(UIBarButtonItem*)sender;
-(void)deleteForwardAction:(UIBarButtonItem*)sender;

-(void)selectAllActionLP:(UILongPressGestureRecognizer *)recognizer;
-(void)copyActionLP:(UILongPressGestureRecognizer *)recognizer;
-(void)pasteActionLP:(UILongPressGestureRecognizer *)recognizer;
-(void)cutActionLP:(UILongPressGestureRecognizer *)recognizer;
-(void)undoActionLP:(UILongPressGestureRecognizer *)recognizer;
-(void)redoActionLP:(UILongPressGestureRecognizer *)recognizer;
-(void)selectActionLP:(UILongPressGestureRecognizer *)recognizer;
-(void)beginningActionLP:(UILongPressGestureRecognizer *)recognizer;
-(void)endingActionLP:(UILongPressGestureRecognizer *)recognizer;
-(void)capitalizeActionLP:(UILongPressGestureRecognizer *)recognizer;
-(void)lowercaseActionLP:(UILongPressGestureRecognizer *)recognizer;
-(void)uppercaseActionLP:(UILongPressGestureRecognizer *)recognizer;
-(void)deleteActionLP:(UILongPressGestureRecognizer *)recognizer;
-(void)boldActionLP:(UILongPressGestureRecognizer *)recognizer;
-(void)italicActionLP:(UILongPressGestureRecognizer *)recognizer;
-(void)underlineActionLP:(UILongPressGestureRecognizer *)recognizer;
-(void)dismissKeyboardActionLP:(UILongPressGestureRecognizer *)recognizer;
-(void)moveCursorLeftActionLP:(UILongPressGestureRecognizer*)recognizer;
-(void)moveCursorRightActionLP:(UILongPressGestureRecognizer*)recognizer;
-(void)moveCursorUpActionLP:(UILongPressGestureRecognizer*)recognizer;
-(void)moveCursorDownActionLP:(UILongPressGestureRecognizer*)recognizer;
-(void)keyboardTypeActionLP:(UILongPressGestureRecognizer *)recognizer;
-(void)defineActionLP:(UILongPressGestureRecognizer*)recognizer;
-(void)runCommandActionLP:(UILongPressGestureRecognizer*)recognizer;
-(void)insertTextActionLP:(UILongPressGestureRecognizer*)recognizer;
-(void)selectLineActionLP:(UILongPressGestureRecognizer*)recognizer;
-(void)selectParagraphActionLP:(UILongPressGestureRecognizer*)recognizer;
-(void)selectSentenceActionLP:(UILongPressGestureRecognizer*)recognizer;
-(void)moveCursorPreviousWordActionLP:(UILongPressGestureRecognizer *)recognizer;
-(void)moveCursorNextWordActionLP:(UILongPressGestureRecognizer *)recognizer;
-(void)moveCursorStartOfLineActionLP:(UILongPressGestureRecognizer *)recognizer;
-(void)moveCursorEndOfLineActionLP:(UILongPressGestureRecognizer *)recognizer;
-(void)moveCursorStartOfParagraphActionLP:(UILongPressGestureRecognizer *)recognizer;
-(void)moveCursorEndOfParagraphActionLP:(UILongPressGestureRecognizer *)recognizer;
-(void)moveCursorStartOfSentenceActionLP:(UILongPressGestureRecognizer *)recognizer;
-(void)moveCursorEndOfSentenceActionLP:(UILongPressGestureRecognizer *)recognizer;
-(UIWindow*)keyWindow;
-(void)translomaticActionLP:(UILongPressGestureRecognizer *)recognizer;
-(void)wasabiActionLP:(UILongPressGestureRecognizer *)recognizer;
-(void)pasitheaActionLP:(UILongPressGestureRecognizer *)recognizer;
-(void)activateLPActions:(UIGestureRecognizer *)recognizer;
-(void)globeActionLP:(UILongPressGestureRecognizer*)recognizer;
-(void)deleteForwardActionLP:(UILongPressGestureRecognizer *)recognizer;

-(void)moveCursorContinuoslyWithDelegate:(id <UITextInput, UITextInputTokenizer>)delegate offset:(int)offset;
-(void)openLog;
-(NSString *)convertColorToString:(UIColor *)colorname;
-(NSString *)getImageNameForActionName:(NSString *)actionname;
-(void)sendShowToastRequestWithMessage:(NSString *)message imagePath:(NSString *)imagepath imageTint:(UIColor *)imagetint width:(int)width height:(int)height positionX:(float)positionX positionY:(float)positionY duration:(double)duration alpha:(float)alpha radius:(float)radius textColor:(UIColor *)textColor backgroundColor:(UIColor *)backgroundColor displayType:(int)displayType;
-(void)triggerImpactAndAnimationWithButton:(UIBarButtonItem *)sender selectorName:(NSString *)selname toastWidthOffset:(int)woffset toastHeightOffset:(int)hoffset;
-(NSDictionary *)locationForMode:(int)mode assistantView:(TUISystemInputAssistantView *)assistantView actionName:(NSString *)actionName;
-(UITextRange *)selectedWordTextRangeWithDelegate:(id<UITextInput>)delegate;
-(UITextRange *)selectedWordTextRangeWithDelegate:(id<UITextInput>)delegate direction:(UITextStorageDirection)direction;
-(UITextRange *)autoDirectionWordSelectedTextRangeWithDelegate:(id<UITextInput> )delegate;

-(UITextRange *)singleWordTextRangeWithDelegate:(id<UITextInput>)delegate direction:(UITextStorageDirection)direction;
-(UITextRange *)lineExtremityTextRangeWithDelegate:(id<UITextInput>)delegate direction:(UITextLayoutDirection)direction;
-(void)moveCursorSingleWordWithDelegate:(id <UITextInput, UITextInputTokenizer>)delegate direction:(UITextStorageDirection)direction;
-(void)moveCursorToLineExtremityWithDelegate:(id <UITextInput, UITextInputTokenizer>)delegate direction:(UITextLayoutDirection)direction;

-(UIWindow*)keyWindow;
- (int)currentCursorPosition:(id <UITextInput, UITextInputTokenizer>)delegate;
-(void)moveCursorWithDelegate:(id <UITextInput, UITextInputTokenizer>)delegate offset:(int)offset;
-(BOOL)isRTLForDelegate:(id <UITextInput, UITextInputTokenizer>)delegate;
-(CPDistributedMessagingCenter *)IPCCenterNamed:(NSString *)centerName;
-(BOOL)isAutoCorrectionEnabled;
-(void)setAutoCorrection:(BOOL)enabled;
-(void)updateAutoCorrection:(NSNotification*)notification;
-(BOOL)isAutoCapitalizationEnabled;
-(void)setAutoCapitalization:(BOOL)enabled;
-(void)updateAutoCapitalization:(NSNotification*)notification;
-(NSDictionary *)getItemWithID:(NSString *)snippetID forKey:(NSString *)keyName identifierKey:(NSString *)identifier;
-(void)runCommand:(NSString *)cmd;
-(NSUInteger)getShortcutIndexWithActionNamed:(NSString *)actionName;
-(BOOL)isValidURL:(NSString *)urlString;
@end
