#!/bin/bash

mkdir /private/var/mobile/Library/Caches/com.udevs.xpad || true
chown mobile:mobile /private/var/mobile/Library/Caches/com.udevs.xpad
chmod 0755 /private/var/mobile/Library/Caches/com.udevs.xpad

exit 0
